/** The National Highways Act, 1956. */
import type { WorkflowDefinition } from "../types";

export const NH_ACT_1956: WorkflowDefinition = {
  act: "NH_ACT_1956",
  name: "National Highways Act 1956",
  citation: "National Highways Act, 1956 (ss.3A–3J), read with LARR 2013 for compensation",
  stages: [
    {
      status: "DRAFT",
      label: "Draft proposal",
      actors: ["LAND_REQUIRING_BODY", "SUPER_ADMIN"],
      slaDays: 30,
      next: ["SUBMITTED"],
      note: "Prepared by NHAI or the highway implementing agency.",
    },
    {
      status: "SUBMITTED",
      label: "Submitted to CALA",
      actors: ["LAND_REQUIRING_BODY", "SUPER_ADMIN"],
      slaDays: 3,
      next: ["DISTRICT_SCRUTINY"],
    },
    {
      status: "DISTRICT_SCRUTINY",
      label: "CALA scrutiny",
      actors: ["LAND_ACQUIRING_AUTHORITY", "DISTRICT_COLLECTOR", "SUPER_ADMIN"],
      slaDays: 21,
      next: ["RETURNED_FOR_CLARIFICATION", "REJECTED", "STATE_APPROVAL"],
      note: "The Competent Authority for Land Acquisition verifies the proposal. No SIA stage under the NH Act.",
    },
    {
      status: "STATE_APPROVAL",
      label: "Ministry / state clearance",
      actors: ["STATE_GOVERNMENT", "CENTRAL_MINISTRY", "SUPER_ADMIN"],
      slaDays: 30,
      next: ["RETURNED_FOR_CLARIFICATION", "REJECTED", "SEC_11_PRELIM_NOTIFICATION"],
    },
    {
      // Reuses the LARR status enum so one engine drives both Acts; the label
      // and section carry the NH Act's own identity.
      status: "SEC_11_PRELIM_NOTIFICATION",
      label: "Section 3A notification",
      section: "s.3A",
      actors: ["LAND_ACQUIRING_AUTHORITY", "SUPER_ADMIN"],
      slaDays: 30,
      next: ["OBJECTIONS"],
      note: "Preliminary notification of intent to acquire land for a national highway.",
    },
    {
      status: "OBJECTIONS",
      label: "Section 3C objections",
      section: "s.3C",
      actors: ["LAND_ACQUIRING_AUTHORITY", "SUPER_ADMIN"],
      slaDays: 21,
      statutoryDays: 21,
      onBreach: "ESCALATE",
      next: ["REJECTED", "SEC_19_DECLARATION"],
      note: "Objections must be filed within 21 days of the s.3A notification — a much shorter window than LARR's 60 days.",
    },
    {
      status: "SEC_19_DECLARATION",
      label: "Section 3D declaration",
      section: "s.3D",
      actors: ["CENTRAL_MINISTRY", "SUPER_ADMIN"],
      slaDays: 30,
      statutoryDays: 365,
      onBreach: "RESCIND",
      next: ["SEC_21_NOTICE"],
      note: "Declaration of acquisition. Must follow the s.3A notification within one year, else it lapses. On publication the land vests absolutely in the Central Government.",
    },
    {
      status: "SEC_21_NOTICE",
      label: "Notice to landowners",
      section: "s.3E",
      actors: ["LAND_ACQUIRING_AUTHORITY", "SUPER_ADMIN"],
      slaDays: 30,
      next: ["AWARD_ENQUIRY"],
      note: "Notice to surrender possession under s.3E.",
    },
    {
      status: "AWARD_ENQUIRY",
      label: "Compensation enquiry",
      section: "s.3G",
      actors: ["LAND_ACQUIRING_AUTHORITY", "SUPER_ADMIN"],
      slaDays: 90,
      next: ["AWARD_DECLARED"],
      note: "CALA determines compensation; where parties disagree it goes to an arbitrator appointed under s.3G(5).",
    },
    {
      status: "AWARD_DECLARED",
      label: "Section 3G award",
      section: "s.3G",
      actors: ["LAND_ACQUIRING_AUTHORITY", "SUPER_ADMIN"],
      slaDays: 30,
      statutoryDays: 365,
      onBreach: "LAPSE",
      next: ["COMPENSATION_DISBURSEMENT"],
      note: "Compensation computed on LARR 2013 principles since the 2015 amendment — market value × multiplier + assets + 100% solatium.",
    },
    {
      status: "COMPENSATION_DISBURSEMENT",
      label: "Compensation disbursement",
      actors: ["LAND_ACQUIRING_AUTHORITY", "DISTRICT_COLLECTOR", "SUPER_ADMIN"],
      slaDays: 90,
      statutoryDays: 90,
      onBreach: "ESCALATE",
      next: ["RNR_IMPLEMENTATION"],
      note: "Paid through PFMS on the real Bhoomi Rashi model.",
    },
    {
      status: "RNR_IMPLEMENTATION",
      label: "Rehabilitation & Resettlement",
      actors: ["REHABILITATION_AUTHORITY", "SUPER_ADMIN"],
      slaDays: 180,
      statutoryDays: 180,
      onBreach: "ESCALATE",
      next: ["POSSESSION"],
      note: "LARR Second Schedule entitlements apply to NH acquisitions too.",
    },
    {
      status: "POSSESSION",
      label: "Possession taken",
      section: "s.3E",
      actors: ["LAND_ACQUIRING_AUTHORITY", "DISTRICT_COLLECTOR", "SUPER_ADMIN"],
      slaDays: 30,
      next: ["CLOSED"],
      note: "Possession only after compensation is paid in full.",
    },
    {
      status: "CLOSED",
      label: "Closed",
      actors: ["SUPER_ADMIN"],
      slaDays: 0,
      next: [],
    },
  ],
};
